language: node_js
node_js:
  - "6.1"
install:
  - gem install sass
  - npm install -g grunt bower
  - npm install
  - bower install
script: grunt build && ./node_modules/.bin/karma start --single-run
